project:
  type: website
  output-dir: docs

website:
  title: "Miquel Serra-Burriel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - research.qmd
      - projects.qmd
      - teaching.qmd

format:
  html:
    theme: simplex
    linkcolor: "#ff3393"
    css: styles.css
    toc: true

editor: visual



