---
title: "CV"
---

### Professional Experience

-   Assistant professor of Epidemiology and Health Economics, Epidemiology, Biostatistics, and Prevention Institute (EBPI), University of Zurich (UZH), February 2025 - Pres.

-   Postdoctoral researcher, Law, therapeutics and regulation, Chair Vokinger, University of Zurich (UZH); January 2022 -- January 2025.

-   Postdoctoral researcher, Epidemiology, Biostatistics, and Prevention Institute (EBPI), University of Zurich (UZH); September 2020 -- January 2025 .

-   Postdoctoral researcher, Center for Research in Health, and Economics (CRES), Pompeu Fabra University (UPF); September 2019 -- August 2020.

-   Research Assistant, Center for Research in Health, and Economics (CRES), Pompeu Fabra University (UPF); September 2015 -- September 2018.

### Education

-   PhD Economics, University of Barcelona; 2019.

-   MSc Health Economics and Health Policy, Barcelona Graduate School of Economics; 2014.

-   BSc Economics, Pompeu Fabra University; 2013.

### Memberships & Miscellaneous

-   Associate editor, methodology: Journal of Hepatology Reports. 2023 -- 2028.

-   Associate editor, Health Economics, Gaceta Sanitaria. 2024 -- 2029.

-   Commissioner for the Lancet Commission on European Liver Diseases: Health Economics. 2019-2021

-   Ad hoc Reviewer for: *The Lancet, Journal of Clinical Epidemiology, Journal of Hepatology, Statistical Methods in Medical Research, European Journal of Health Economics, Antimicrobial Resistance and Infection Control, BMC Health Services Research, Spine, Endoscopy, Liver International, BMC Surgery, BMC Infectious diseases, Neurosurgery, Clinical Gastroenterology and Hepatology*.

-   Grant's reviewer for: ISCIII (2019), Basque Country Government (2020).

-   Spanish Health Economics Association Scientific Committee Member (2021 -- 2023).

#### Scientific societies

-   International Society for Pharmacoeconomics and Outcomes Research (ISPOR)

-   Society for Epidemiologic Research (SER)

-   Spanish Epidemiology Society (SEE)

-   Spanish Health Economics Association (AES)
