---
title: "Research"
---

# Peer-reviewed articles

Articles are organized topic-wise, chronologically sorted, and categorized according to their: 🔶 causal, 🟡 predictive, 🟦 descriptive, and/or 🟢 modelling approach.

## Health Economics, Policy & Regulation

-   Glaus, Camille E G, **Miquel Serra-Burriel**, Stacie B Dusetzina, and Kerstin N Vokinger. 2024. "Time from Approval to Reimbursement of New Drugs: A Comparative Analysis Between the United States, England, Germany, France, and Switzerland (2011--2022)." *Annals of Internal Medicine* 177 (September). American College of Physicians: 1442--44. doi:[10.7326/ANNALS-24-00614](https://doi.org/10.7326/ANNALS-24-00614). 🟦

-   Nussli, Emanuel, **Miquel Serra-Burriel**, and Kerstin N. Vokinger. 2024."Comparative Analysis of Drug Shortages in the US and Germany(2016 -- 2023)" *Journal of Law, Medicine and Ethics* 52 (2): 488--97. doi:[10.1017/jme.2024.105](https://doi.org/10.1017/jme.2024.105). 🟦

-   **Serra-Burriel, Miquel**, Nicolau Martin-Bassols, Gellért Perényi, and Kerstin N. Vokinger. 2024. "Drug Prices After Patent Expirations in High-Income Countries and Implications for Cost-Effectiveness Analyses." *JAMA Health Forum* 5 (8): e242530--30. doi:[10.1001/jamahealthforum.2024.2530](https://doi.org/10.1001/jamahealthforum.2024.2530). 🔶🟢

-   Vokinger, Kerstin N, **Miquel Serra-Burriel**, Camille E G Glaus,Ulrich-Peter Rohr, Thomas J Hwang, Simon Dalla Torre di Sanguinetto, andAaron S Kesselheim. 2023. "Regulatory Review Duration and Differences in Submission Times of Drugs in the United States and Europe, 2011 to 2020." *Annals of Internal Medicine* 176(October). American College of Physicians: 1413--18. doi:[10.7326/M23-0623](https://doi.org/10.7326/M23-0623). 🟦

-   **Serra-Burriel, Miquel**, Luca Locher, and Kerstin N. Vokinger. 2024."Development Pipeline and Geographic Representation of Trials for Artificial Intelligence/Machine Learning--Enabled Medical Devices (2010to 2023)." *NEJM AI* 1 (1): AIp2300038. doi:[10.1056/AIpc2300038](https://doi.org/10.1056/AIpc2300038). 🟦

-   Aebersold, Helena, Fabienne Foster-Witassek, **Miquel Serra-Burriel**, Beat Brüngger, Stefanie Aeschbacher, Jürg-Hans Beer, Eva Blozik, Manuel Blum,Leo Bonati, David Conen, Giulio Conte, Stefan Felder, Carola Huber,Michael Kuehne, Giorgio Moschovitis, Andreas Mueller, Rebecca EPaladini, Tobias Reichlin, Nicolas Rodondi, Anne Springer, AnninaStauber, Christian Sticherling, Thomas Szucs, Stefan Osswald, andMatthias Schwenkglenks. 2023. "Estimating the Cost Impact of Atrial Fibrillation Using a Prospective Cohort Study and Population-Based Controls." *BMJ Open* 13 (9). British Medical Journal Publishing Group. doi:[10.1136/bmjopen-2023-072080](https://doi.org/10.1136/bmjopen-2023-072080). 🟦

-   Vokinger, Kerstin N, Camille E G Glaus, Aaron S Kesselheim, **Miquel Serra-Burriel**, Joseph S Ross, and Thomas J Hwang. 2023."Therapeutic Value of First Versus Supplemental Indications of Drugs in US and Europe (2011-20): Retrospective Cohort Study."*BMJ* 382. BMJ Publishing Group Ltd. doi:[10.1136/bmj-2022-074166](https://doi.org/10.1136/bmj-2022-074166). 🟦

-   **Serra-Burriel, Miquel**, Gellért Perényi, Yannic Laube, Aaron P Mitchell,and Kerstin N Vokinger. 2023. "The Cancer Premium; ExplainingDifferences in Prices for Cancer Vs Non-Cancer Drugs with Efficacy and Epidemiological Endpoints in the US, Germany, and Switzerland: A Cross Sectional Study." *eClinicalMedicine* 61 (July). Elsevier.doi:[10.1016/j.eclinm.2023.102087](https://doi.org/10.1016/j.eclinm.2023.102087). 🟦

-   Aebersold, Helena, **Miquel Serra-Burriel**, Fabienne Foster-Wittassek,Giorgio Moschovitis, Stefanie Aeschbacher, Angelo Auricchio, Jürg Hans Beer, Eva Blozik, Leo H Bonati, David Conen, Stefan Felder, Carola AHuber, Michael Kuehne, Andreas Mueller, Jolanda Oberle, Rebecca E Paladini, Tobias Reichlin, Nicolas Rodondi, Anne Springer, Annina Stauber, Christian Sticherling, Thomas D Szucs, Stefan Osswald, and Matthias Schwenkglenks. 2023. "Patient Clusters and Cost Trajectories in the Swiss Atrial Fibrillation Cohort."*Heart* 109 (10). BMJ Publishing Group Ltd: 763--70. doi:[10.1136/heartjnl-2022-321520](https://doi.org/10.1136/heartjnl-2022-321520). 🟦

-   Carl, David L., Yannic Laube, **Miquel Serra-Burriel**, Huseyin Naci,Wolf-Dieter Ludwig, and Kerstin N. Vokinger. 2022. "Comparison of Uptake and Prices of Biosimilars in the US, Germany, and Switzerland." *JAMA Network Open* 5 (12): e2244670--70.doi:[10.1001/jamanetworkopen.2022.44670](https://doi.org/10.1001/jamanetworkopen.2022.44670). 🟦

-   **Serra-Burriel, Miquel**, Isabel Hurtado, Gabriel Sanfélix-Gimeno, AníbalGarcía-Sempere, and Salvador Peiró. 2021. "Cost-Sharing Increase,Medication Adherence, and Hospitalizations in Schizophrenia Patients: ANatural Experiment." *Clinical Pharmacology & Therapeutics* 110 (6): 1490--97. doi:<https://doi.org/10.1002/cpt.2283>. 🔶

-   Brüngger, Beat, Caroline Bähler, Matthias Schwenkglenks, Agne Ulyte,Holger Dressel, Viktor von Wyl, Oliver Gruebner, Wenjia Wei, **Miquel Serra-Burriel,** and Eva Blozik. 2021. "Surgical Procedures in Inpatient Versus Outpatient Settings and Its Potential Impact on Follow-up Costs." *Health Policy* 125 (10): 1351--58.doi:<https://doi.org/10.1016/j.healthpol.2021.07.006>. 🔶

-   **Serra-Burriel, Miquel**, Carlos Campillo-Artero, Antonella Agodi, Martina Barchitta, and Guillem López-Casasnovas. 2022. "Association Between Antibiotic Resistance in Intensive Care Unit (ICU)--Acquired Infections and Excess Resource Utilization: Evidence from Spain, Italy, and Portugal." *Infection Control & Hospital Epidemiology* 43. Cambridge University Press: 1360--67. doi:[DOI:10.1017/ice.2021.429](https://doi.org/DOI:%2010.1017/ice.2021.429). 🔶

-   **Serra-Burriel, Miquel**, Isabel Graupera, Pere Torán, Maja Thiele,Dominique Roulot, Vincent Wai-Sun Wong, Indra Neil Guha, NúriaFabrellas, Anita Arslanow, Carmen Expósito, Rosario Hernández, GraceLai-Hung Wong, David Harman, Sarwa Darwish Murad, Aleksander Krag,Guillem Pera, Paolo Angeli, Peter Galle, Guruprasad P. Aithal, LlorençCaballeria, Laurent Castera, Pere Ginès, and Frank Lammert. 2019."Transient Elastography for Screening of Liver Fibrosis:Cost-Effectiveness Analysis from Six Prospective Cohorts in Europe and Asia." *Journal of Hepatology* 71 (6): 1141--51. doi:<https://doi.org/10.1016/j.jhep.2019.08.019>. 🟡🟢

-   Costa-Ramón, Ana María, Ana Rodríguez-González, **Miquel Serra-Burriel**, and Carlos Campillo-Artero. 2018. "It's about Time: Cesarean Sections and Neonatal Health." *Journal of Health Economics* 59: 46--59. doi:<https://doi.org/10.1016/j.jhealeco.2018.03.004>. 🔶

## Clinical Medicine & Epidemiology

-   Locher, Luca, **Miquel Serra-Burriel**, Dario Trapani, Emanuel Nussli, and Kerstin N Vokinger. 2024. "Why Effect Sizes Are Systematically Larger for Progression-Free Survival Than Overall Survival in Cancer Drug Trials: Prognostic Scores as a Way Forward." *European Journal of Cancer*, 115106. doi:[10.1016/j.ejca.2024.115106](https://doi.org/10.1016/j.ejca.2024.115106). 🟦 🟢

-   Unterfrauner, Ines, Javier Muñoz Laguna, **Miquel Serra-Burriel**, Jakob M Burgstaller, Ilker Uçkay, Mazda Farshad, and Cesar A Hincapié. 2024. "Fusion Versus Decompression Alone for Lumbar Degenerative Spondylolisthesis and Spinal Stenosis: A Target Trial Emulation with Index Trial Benchmarking." *European Spine Journal* 33: 4281--91. doi:[10.1007/s00586-024-08495-0](https://doi.org/10.1007/s00586-024-08495-0). 🔶

-   Foster‐Witassek, Fabienne, Helena Aebersold, Stefanie Aeschbacher, Peter Ammann, Jürg H Beer, Eva Blozik, Leo H Bonati, Mattia Cattaneo, Michael Coslovsky, Stefan Felder, Giorgio Moschovitis, Andreas Müller, Seraina Netzer, Rebecca E Paladini, Tobias Reichlin, Nicolas Rodondi, AnninaStauber, Christian Sticherling, Thomas Szucs, David Conen, MichaelKühne, Stefan Osswald, **Miquel Serra‐Burriel**, Matthias Schwenkglenks, and the Swiss‐AF Investigators. 2023. "Longitudinal Changes in Health‐related Quality of Life in Patients with Atrial Fibrillation." *Journal of the American Heart Association*12 (November). Wiley: e031872. doi:[10.1161/JAHA.123.031872](https://doi.org/10.1161/JAHA.123.031872). 🟦

-   Ginès, Pere, Maja Thiele, Isabel Graupera, **Miquel Serra-Burriel**, Robert J. de Knegt, Frank Lammert, Laurent Castera, Marko Korenjak, Patrick S.Kamath, Ivica Grgurević, Salvatore Piano, Núria Fabrellas, Anita Arslanow, and Aleksander Krag. 2023. "Screening for Fibrosis to Diagnose Liver Diseases Early: The LIVERSCREEN Project."*Nature Medicine* 29 (April). Nature Research: 774--75. doi:[10.1038/s41591-023-02265-z](https://doi.org/10.1038/s41591-023-02265-z). 🟦

-   Strassmann, Alexandra, Yunus Çolak, **Miquel Serra-Burriel**, Børge G Nordestgaard, Alexander Turk, Shoaib Afzal, and Milo A Puhan. 2023."Nationwide Indoor Smoking Ban and Impact on Smoking Behaviour and Lung Function: A Two-Population Natural Experiment."*Thorax* 78 (2). BMJ Publishing Group Ltd: 144--50. doi:[10.1136/thoraxjnl-2021-218436](https://doi.org/10.1136/thoraxjnl-2021-218436). 🔶

-   Bassegoda, Octavi, Jesús Rivera-Esteban, Isabel Serra, Rosa Morillas,Teresa Broquetas, Mercedes Vergara, Adrià Rodriguez, Carles Aracil,Silvia Virolés, Jose A. Carrión, Albert Pardo, Sergio Rodríguez-Tajes, **Miquel Serra-Burriel**, Juan M. Pericàs, Salvador Augustin, Pere Ginès,and Isabel Graupera. 2022. "High Frequency of Acute Decompensation and Cancer in Patients with Compensated Cirrhosis Due to Nonalcoholic Fatty Liver Disease: A Retrospective Cohort Study."*Hepatology Communications* 6 (November). John Wiley; Sons Inc:3212--22. doi:[10.1002/hep4.2056](https://doi.org/10.1002/hep4.2056). 🟦

-   Graupera, Isabel, Maja Thiele, **Miquel Serra-Burriel**, Llorenç Caballeria, Dominique Roulot, Grace Lai-Hung Wong, Núria Fabrellas, Indra Neil Guha, Anita Arslanow, Carmen Expósito, Rosario Hernández, Guruprasad Padur Aithal, Peter R. Galle, Guillem Pera, Vincent Wai-Sun Wong, FrankL ammert, Pere Ginès, Laurent Castera, and Aleksander Krag. 2022."Low Accuracy of FIB-4 and NAFLD Fibrosis Scores for Screening for Liver Fibrosis in the Population." *Clinical Gastroenterology and Hepatology* 20 (11): 2567--2576.e6. doi:<https://doi.org/10.1016/j.cgh.2021.12.034>. 🟡

-   Bassegoda, Octavi, Pol Olivas, Laura Turco, Mattias Mandorfer, **Miquel Serra-Burriel**, Luis Tellez, Wilhelmus Kwanten, Alexia Laroyenne, Oana Farcau, Edilmar Alvarado, Lucile Moga, Elise Vuille-Lessard, JoseIgnacio Fortea, Luis Ibañez, Giulia Tosetti, Thomas Vanwolleghem, Hélène Larrue, Diego Burgos-Santamaría, Horia Stefanescu, Rafael Paternostro, Annalisa Cippitelli, Sabela Lens, Salvador Augustin, Elba Llop, Wim Laleman, Jonel Trebicka, Johannes Chang, Helena Masnou, AlexanderZipprich, Francesca Miceli, Georg Semmler, Xavier Forns, Massimo Primignani, Rafael Bañares, Angela Puente, Annalisa Berzigotti, PierreEmmanuel Rautou, Candid Villanueva, Pere Ginès, J. C. Garcia-Pagan,Bogdan Procopet, Cristophe Bureau, Agustin Albillos, Sven Francque,Thomas Reiberger, Filippo Schepis, Isabel Graupera, and Virginia Hernandez-Gea. 2022. "Decompensation in Advanced Nonalcoholic Fatty Liver Disease May Occur at Lower Hepatic Venous Pressure Gradient Levels Than in Patients with Viral Disease." *Clinical Gastroenterology and Hepatology* 20 (10): 2276--2286.e6. doi:<https://doi.org/10.1016/j.cgh.2021.10.023>. 🟦

-   Sequeira-Aymar, Ethel, Angeline Cruz, **Miquel Serra-Burriel**, Ximena diLollo, Alessandra Queiroga Gonçalves, Laura Camps-Vilà, Marta M Monclus-Gonzalez, Elisa M Revuelta-Muñoz, Nuria Busquet-Solé, Susana Sarriegui-Domínguez, Aina Casellas, Maria Rosa Dalmau Llorca, Carina Aguilar-Martín, Constanza Jacques-Aviñó, Sally Hargreaves, AnaRequena-Mendez, and the CRIBMI (IS-MiHealth) Working Group. 2022."Improving the Detection of Infectious Diseases in at-Risk Migrants with an Innovative Integrated Multi-Infection Screening Digital Decision Support Tool (IS-MiHealth) in Primary Care: A Pilot Cluster-Randomized-Controlled Trial." *Journal of Travel Medicine* 29 (October): taab100. doi:[10.1093/jtm/taab100](https://doi.org/10.1093/jtm/taab100). 🔶🟡

-   Frei, Anja, Thomas Radtke, Kaba Dalla Lana, Patrick Brun, Thomas Sigrist, Marc Spielmanns, Swantje Beyer, Thomas F. Riegler, GilbertBüsching, Sabine Spielmanns, Ramona Kunz, Tamara Cerini, Julia Braun, Yuki Tomonaga, **Miquel Serra-Burriel**, Ashley Polhemus, and Milo A. Puhan. 2022. "Effectiveness of a Long-Term Home-Based Exercise Training Program in Patients with COPD After Pulmonary Rehabilitation: A Multicenter Randomized Controlled Trial." *Chest* 162 (6):1277--86. doi:<https://doi.org/10.1016/j.chest.2022.07.026>. 🔶

-   Graupera, Isabel, Maja Thiele, Ann T Ma, Miquel Serra-Burriel, JuditPich, Núria Fabrellas, Llorenç Caballeria, Robert J de Knegt, IvicaGrgurevic, Mathias Reichert, Dominique Roulot, Jörn M Schattenberg, JuanM Pericas, Paolo Angeli, Emmanuel A Tsochatzis, Indra Neil Guha,Montserrat Garcia-Retortillo, Rosa M Morillas, Rosario Hernández, JordiHoyo, Matilde Fuentes, Anita Madir, Adrià Juanola, Anna Soria, MartaJuan, Marta Carol, Alba Diaz, Sönke Detlefsen, Pere Toran, Guillem Pera, Céline Fournier, Anne Llorca, Phillip N Newsome, Michael Manns, Harry Jde Koning, Feliu Serra-Burriel, Fernando Cucchietti, Anita Arslanow,Marko Korenjak, Laurens van Kleef, Josep Lluis Falcó, Patrick S Kamath,Tom H Karlsen, Laurent Castera, Frank Lammert, Aleksander Krag, PereGinès, Marifé Alvarez, Peter Andersen, Paolo Angeli, Alba Ardèvol, AnitaArslanow, Luca Beggiato, Zahia Ben Abdesselam, Lucy Bennett, BajihaBoutouria, Alessandra Brocca, M Teresa Broquetas, Llorenc Caballeria,Valeria Calvino, Judith Camacho, Aura Capdevila, Marta Carol, LaurentCastera, Marta Cervera, Fernando Cucchietti, Anna de Fuentes, Rob deKnegt, Sonke Detlefsen, Alba Diaz, José Diéguez Bande, Vanessa Esnault,Núria Fabrellas, Josep lluis Falco, Rosa Fernández, Celine Fournier,Matilde Fuentes, Peter Galle, Edgar García, MontserratGarcía-Retortillo, Esther Garrido, Pere Ginès, Rosa Gordillo Medina,Jordi Gratacós-Gines, Isabel Graupera, Ivica Grgurevic, Indra Neil Guha,Eva Guix, Rebecca Harris, Elena Hernández Boluda, RosarioHernández-Ibañez, Jordi Hoyo, Arfan Ikram, Simone Incicco, MadsIsraelsen, Marta Juan, Adria Juanola, Ralf Kaiser, Patrick S Kamath, TomH Karlsen, Maria Kjærgaard, Harry J de Koning, Marko Korenjak,Aleksander Krag, Johanne Kragh Hansen, Marcin Krawczyk, Irina Lambert,Frank Lammert, Philippe Laboulaye, Simon Langkjær Sørensen, CristinaLaserna-Jiménez, Sonia Lazaro Pi, Elsa Ledain, Vincent Levy, VanessaLondoño, Guirec Loyer, Anne Llorca, Ann T Ma, Anita Madir, MichaelManns, Denise Marshall, M Lluïsa Martí, Sara Martínez, Ricard MartínezSala, Roser Masa Font, Jane Møller Jensen, Rosa M Morillas, Laura Muñoz,Ruth Nadal, Laura Napoleone, J M Navarrete, Phillip N Newsome, VibekeNielsen, Martina Pérez, Juan Manuel Pericas Pulido, Salvatore Piano,Judit Pich, Judit Presas Escobet, Elisa Pose, Katrine Prier Lindvig,Matthias Reichert, Carlota Riba, Dominique Roulot, Ana Belén Rubio,Maria Sánchez-Morata, Jörn Schattenberg, Feliu Serra-Burriel, **Miquel Serra-Burriel**, Louise Skovborg Just, Milan Sonneveld, Anna Soria,Christiane Stern, Patricia Such, Maja Thiele, Pere Toran, AntoniTorrejón, Marta Tonon, Emmanuel A Tsochatzis, Laurens van Kleef, Paulienvan Wijngaarden, Vanessa Velázquez, Ana Viu, Susanne Nicole Weber,Tracey Wildsmith, and for the LiverScreen Consortium investigators.2022. "LiverScreen Project: Study Protocol for Screening for Liver Fibrosis in the General Population in European Countries."*BMC Public Health* 22: 1385. doi:[10.1186/s12889-022-13724-6](https://doi.org/10.1186/s12889-022-13724-6). 🟦

-   Keys, Matthew T, **Miquel Serra-Burriel**, Natalia Martínez-Lizaga, Maria Pellisé, Francesc Balaguer, Ariadna Sánchez, Enrique Bernal-Delgado, and Antoni Castells. 2020. "Population-Based Organized Screening by Faecal Immunochemical Testing and Colorectal Cancer Mortality: A Natural Experiment." *International Journal of Epidemiology* 50(1): 143--55. doi:[10.1093/ije/dyaa166](https://doi.org/10.1093/ije/dyaa166). 🔶

-   González-Suárez, Begoña, Mario Pagés, Isis Karina Araujo, CristinaRomero, Cristina Rodríguez de Miguel, Juan Ramón Ayuso, Àngels Pozo,Maria Vila-Casadesús, Anna Serradesanferm, Àngels Ginès, Glòria Fernández-Esparrach, Maria Pellisé, María López-Cerón, David Flores,Henry Córdova, Oriol Sendino, Jaume Grau, Josep Llach, **Miquel Serra-Burriel**, Andrés Cárdenas, Francesc Balaguer, and Antoni Castells.2020. "Colon Capsule Endoscopy Versus CT Colonography in FIT-Positive Colorectal Cancer Screening Subjects: A Prospective Randomised Trial---the VICOCA Study." *BMC Medicine* 18:255. doi:[10.1186/s12916-020-01717-4](https://doi.org/10.1186/s12916-020-01717-4). 🔶

-   **Serra-Burriel, Miquel**, Matthew Keys, Carlos Campillo-Artero. 2020."Impact of Multi-Drug Resistant Bacteria on Economic and Clinical Outcomes of Healthcare-Associated Infections in Adults: Systematic Review and Meta-Analysis." *PLOS ONE* 15 (1). PublicLibrary of Science: 1--14. doi:[10.1371/journal.pone.0227139](https://doi.org/10.1371/journal.pone.0227139). 🟡

## Decision-Support Systems & Heuristics

-   **Serra-Burriel, Miquel**, Adrià Juanola, Feliu Serra-Burriel, Maja Thiele,Isabel Graupera, Elisa Pose, Guillem Pera, Ivica Grgurevic, LlorençCaballeria, Salvatore Piano, Laurens van Kleef, Mathias Reichert,Dominique Roulot, Juan M Pericàs, Jörn M Schattenberg, Emmanuel ATsochatztis, Indra Neil Guha, Montserrat Garcia-Retortillo, RosarioHernández, Jordi Hoyo, Matilde Fuentes, Carmen Expósito, Alba Martínez,Patricia Such, Anita Madir, Sönke Detlefsen, Marta Tonon, AndreaMartini, Ann T Ma, Judith Pich, Eva Bonfill, Marta Juan, Anna Soria,Marta Carol, Jordi Gratacós-Ginès, Rosa M Morillas, Pere Toran, J MNavarrete, Antoni Torrejón, Céline Fournier, Anne Llorca, AnitaArslanow, Harry J de Koning, Fernando Cucchietti, Michael Manns, PhillipN Newsome, Rubén Hernáez, Alina Allen, Paolo Angeli, Robert J de Knegt,Tom H Karlsen, Peter Galle, Vincent Wai-Sun Wong, Núria Fabrellas,Laurent Castera, Aleksander Krag, Frank Lammert, Patrick S Kamath, PereGinès, Marifé Alvarez, Peter Andersen, Paolo Angeli, Alba Ardèvol, AnitaArslanow, Luca Beggiato, Zahia Ben Abdesselam, Lucy Bennett, BajihaBoutouria, Alessandra Brocca, M Teresa Broquetas, Llorenç Caballeria,Valeria Calvino, Judith Camacho, Aura Capdevila, Marta Carol, LaurentCastera, Marta Cervera, Fernando Cucchietti, Anna de Fuentes, Rob deKnegt, Harry J de Koning, Sonke Detlefsen, Alba Diaz, José DiéguezBande, Vanessa Esnault, Núria Fabrellas, Josep Lluis Falcó, RosaFernández, Céline Fournier, Matilde Fuentes, Peter Galle, Edgar García,Montserrat García-Retortillo, Esther Garrido, Pere Ginès, Rosa GordilloMedina, Jordi Gratacós-Ginès, Isabel Graupera, Ivica Grgurevic, IndraNeil Guha, Eva Guix, Johanne Kragh Hansen, Rebecca Harris, ElenaHernández Boluda, Rosario Hernández-Ibañez, Jordi Hoyo, Arfan Ikram,Simone Incicco, Mads Israelsen, Marta Juan, Adrià Juanola, Ralf Kaiser,Patrick S Kamath, Tom H Karlsen, Maria Kjærgaard, Marko Korenjak,Aleksander Krag, Marcin Krawczyk, Philippe Laboulaye, Irina Lambert,Frank Lammert, Simon Langkjær Sørensen, Cristina Laserna-Jiménez, SoniaLazaro Pi, Elsa Ledain, Vincent Levy, Katrine Prier Lindvig, AnneLlorca, Vanessa Londoño, Guirec Loyer, Ann T Ma, Anita Madir, MichaelManns, Denise Marshall, M Lluïsa Martí, Sara Martínez, Ricard MartínezSala, Roser Masa-Font, Jane Møller Jensen, Rosa M Morillas, Laura Muñoz,Ruth Nadal, Laura Napoleone, J M Navarrete, Phillip N Newsome, VibekeNielsen, Martina Pérez, Juan Manuel Pericás-Pulido, Salvatore Piano,Judit Pich, Elisa Pose, Judit Presas Escobet, Matthias Reichert, CarlotaRiba, Dominique Roulot, Ana Belén Rubio, Maria Sánchez-Morata, JörnSchattenberg, Miquel Serra-Burriel, Feliu Serra-Burriel, Louise SkovborgJust, Milan Sonneveld, Anna Soria, Christiane Stern, Patricia Such, MajaThiele, Marta Tonon, Pere Toran, Antoni Torrejón, Emmanuel A Tsochatzis,Laurens van Kleef, Paulien van Wijngaarden, Vanessa Velázquez, Ana Viu,Susanne Nicole Weber, and Tracey Wildsmith. 2023. "Development,Validation, and Prognostic Evaluation of a Risk Score for Long-Term Liver-Related Outcomes in the General Population: A Multicohort Study." *The Lancet* 402 (September). Elsevier: 988--96.doi:[10.1016/S0140-6736(23)01174-1](https://doi.org/10.1016/S0140-6736(23)01174-1). 🟡

-   Pellisé, Ferran, Alba Vila-Casademunt, Susana Núñez-Pereira, SleimanHaddad, Justin S Smith, Michael P Kelly, Ahmet Alanay, ChristopherShaffrey, Javier Pizones, Çaglar Yilgor, Ibrahim Obeid, Douglas Burton,Frank Kleinstück, Tamas Fekete, Shay Bess, Munish Gupta, Markus Loibl,Eric O Klineberg, Francisco J Sánchez Pérez-Grueso, **Miquel Serra-Burriel**, Christopher P Ames, and International Spine Study Group European Spine Study Group. 2022. "Surgeons' Risk Perception in ASD Surgery: The Value of Objective Risk Assessment on Decision Making and Patient Counselling." *European Spine Journal* 31:1174--83. doi:[10.1007/s00586-022-07166-2](https://doi.org/10.1007/s00586-022-07166-2). 🟦

-   Sánchez, Ariadna, Victorine H Roos, Matilde Navarro, Marta Pineda, BertaCaballol, Lorena Moreno, Sabela Carballal, Lorena Rodríguez-Alonso,Teresa Ramon y Cajal, Gemma Llort, Virginia Piñol, AdriàLópez-Fernández, Inmaculada Salces, Maria Dolores Picó, Laura Rivas,Luis Bujanda, Marta Garzon, Angeles Pizarro, Eva Martinez de Castro,Maria Jesus López-Arias, Carmen Poves, Catalina Garau, DanielRodriguez-Alcalde, Maite Herraiz, Cristina Alvarez-Urrutia, AndresDacal, Marta Carrillo-Palau, Lucia Cid, Marta Ponce, EvaBarreiro-Alonso, Esteban Saperas, Elena Aguirre, Cristina Romero,Barbara Bastiaansen, Maribel Gonzalez-Acosta, Blai Morales-Romero,Teresa Ocaña, Liseth Rivero-Sánchez, Gerhard Jung, Xavier Bessa, JoaquinCubiella, Rodrigo Jover, Francisco Rodríguez-Moranta, Judith Balmaña,Joan Brunet, Antoni Castells, Evelien Dekker, Gabriel Capella, **Miquel Serra-Burriel,** Leticia Moreira, Maria Pellise, and Francesc Balaguer.2022. "Quality of Colonoscopy Is Associated with Adenoma Detection and Postcolonoscopy Colorectal Cancer Prevention in Lynch Syndrome." *Clinical Gastroenterology and Hepatology* 20:611--621.e9. doi:<https://doi.org/10.1016/j.cgh.2020.11.002>. 🔶

-   Wondra, James P I I, Michael P Kelly, Jacob Greenberg, Elizabeth LYanik, Christopher P Ames, Ferran Pellise, Alba Vila-Casademunt, JustinS Smith, Shay Bess, Christopher I Shaffrey, Lawrence G Lenke, **Miquel Serra-Burriel**, and Keith H Bridwell. 2023. "Validation of Adult Spinal Deformity Surgical Outcome Prediction Tools in Adult SymptomaticLumbar Scoliosis." *Spine* 48. <https://doi.org/10.1097/brs.0000000000004416>. 🟡

-   Pellisé, Ferran, **Miquel Serra-Burriel**, Alba Vila-Casademunt, Jeffrey LGum, Ibrahim Obeid, Justin S Smith, Frank S Kleinstück, Shay Bess,Javier Pizones, Virginie Lafage, Francisco Javier S Pérez-Grueso, FrankJ Schwab, Douglas C Burton, Eric O Klineberg, Christopher I Shaffrey,Ahmet Alanay, and Christopher P Ames. 2022. "Quality Metrics inAdult Spinal Deformity Surgery over the Last Decade: A Combined Analysis of the Largest Prospective Multicenter Data Sets." *Journal of Neurosurgery: Spine* 36. American Association of Neurological Surgeons: 226--34. doi:<https://doi.org/10.3171/2021.3.SPINE202140>. 🟡

-   Vives, Marc-Lluís, Tania Fernandez-Navia, Jordi J. Teixidó, and **Miquel Serra-Burriel**. 2021. "Lenience Breeds Strictness: The Generosity-Erosion Effect in Hiring Decisions." *Science Advances* 7 (17): eabe2045. doi:[10.1126/sciadv.abe2045](https://doi.org/10.1126/sciadv.abe2045). 🔶

-   Núñez-Pereira, Susana, **Miquel Serra-Burriel,** Alba Vila-Casademunt,Kazunori Hayashi, Sleiman Haddad, Javier Pizones, Frank Kleinstück, Ibrahim Obeid, Ahmet Alanay, Ferran Pellisé, and European Spine Study Group. 2021. "The Dynamics of Satisfaction in Surgical and Non-Surgical Adult Spinal Deformity Patients." *European Spine Journal* 30: 1235--46. doi:[10.1007/s00586-021-06816-1](https://doi.org/10.1007/s00586-021-06816-1). 🟦

-   Duran-Sanchon, Saray, Lorena Moreno, Javier Gómez-Matas, Josep M. Augé, **Miquel Serra-Burriel**, Míriam Cuatrecasas, Leticia Moreira, AnnaSerradesanferm, Àngels Pozo, Jaume Grau, Maria Pellisé, MeritxellGironella, and Antoni Castells. 2021. "Fecal MicroRNA-BasedAlgorithm Increases Effectiveness of Fecal Immunochemical Test--Based Screening for Colorectal Cancer." *Clinical Gastroenterology and Hepatology* 19 (2): 323--330.e1. doi:<https://doi.org/10.1016/j.cgh.2020.02.043>. 🟡

-   Ames, Christopher P, Justin S Smith, Jeffrey L Gum, Michael Kelly, AlbaVila-Casademunt, Douglas C Burton, Richard Hostin, Samrat Yeramaneni,Virginie Lafage, Frank J Schwab, Christopher I Shaffrey, Shay Bess,Ferran Pellisé, and **Miquel Serra-Burriel**. 2020. "Utilization of Predictive Modeling to Determine Episode of Care Costs and to Accurately Identify Catastrophic Cost Nonwarranty Outlier Patients in Adult Spinal Deformity Surgery: A Step Toward Bundled Payments and Risk Sharing." *Spine* 45. doi: [10.1097/BRS.0000000000003242](https://journals.lww.com/spinejournal/fulltext/2020/03010/utilization_of_predictive_modeling_to_determine.7.aspx). 🟡

-   Duran-Sanchon, Saray, Lorena Moreno, Javier Gómez-Matas, Josep M. Augé, **Miquel Serra-Burriel**, Míriam Cuatrecasas, Leticia Moreira, AnnaSerradesanferm, Àngels Pozo, Jaume Grau, Maria Pellisé, MeritxellGironella, and Antoni Castells. 2021. "Fecal MicroRNA-Based Algorithm Increases Effectiveness of Fecal Immunochemical Test--Based Screening for Colorectal Cancer." *Clinical Gastroenterology and Hepatology* 19 (2): 323--330.e1. doi:<https://doi.org/10.1016/j.cgh.2020.02.043>. 🟡

-   Ames, Christopher P, Justin S Smith, Ferran Pellisé, Michael Kelly,Jeffrey L Gum, Ahmet Alanay, Emre Acaroğlu, Francisco Javier SánchezPérez-Grueso, Frank S Kleinstück, Ibrahim Obeid, Alba Vila-Casademunt,Christopher I Shaffrey, Douglas C Burton, Virginie Lafage, Frank JSchwab, Christopher I Shaffrey, Shay Bess, **Miquel Serra-Burriel**, European Spine Study Group, and International Spine Study Group. 2019."Development of Predictive Models for All Individual Questions of SRS-22R After Adult Spinal Deformity Surgery: A Step Toward Individualized Medicine." *European Spine Journal* 28:1998--2011. doi:[10.1007/s00586-019-06079-x](https://doi.org/10.1007/s00586-019-06079-x). 🟡

## Reviews, Letters & Editorials

-   Ginès, Pere, and **Miquel Serra-Burriel**. 2024. "Glucagon-Like Peptide-1 Receptor Agonists for Treatment of Steatotic Liver Disease in Patients with Type 2 Diabetes Mellitus: Growing Evidence but Not yet There." *Gastroenterology* 167 (September). Elsevier: 653--55. doi:[10.1053/j.gastro.2024.05.030](https://doi.org/10.1053/j.gastro.2024.05.030).

-   Karlsen, Tom H, Nick Sheron, Shira Zelber-Sagi, Patrizia Carrieri,Geoffrey Dusheiko, Elisabetta Bugianesi, Rachel Pryke, Sharon JHutchinson, Bruno Sangro, Natasha K Martin, Michele Cecchini, MaeAshworth Dirac, Annalisa Belloni, **Miquel Serra-Burriel**, Cyriel Y Ponsioen, Brittney Sheena, Alienor Lerouge, Marion Devaux, Nick Scott, Margaret Hellard, Henkjan J Verkade, Ekkehard Sturm, Giulio Marchesini,Hannele Yki-Järvinen, Chris D Byrne, Giovanni Targher, Aviad Tur-Sinai,Damon Barrett, Michael Ninburg, Tatjana Reic, Alison Taylor, Tim Rhodes,Carla Treloar, Claus Petersen, Christoph Schramm, Robert Flisiak,Marieta Y Simonova, Albert Pares, Philip Johnson, Alessandro Cucchetti,Isabel Graupera, Christos Lionis, Elisa Pose, Núria Fabrellas, Ann T Ma,Juan M Mendive, Vincenzo Mazzaferro, Harry Rutter, Helena Cortez-Pinto,Deirdre Kelly, Robyn Burton, Jeffrey V Lazarus, Pere Ginès, Maria Buti,Philip N Newsome, Patrizia Burra, and Michael P Manns. 2022. "TheEASL--Lancet Liver Commission: Protecting the Next Generation of Europeans Against Liver Disease Complications and Premature Mortality." *The Lancet* 399 (January). Elsevier: 61--116.doi:[10.1016/S0140-6736(21)01701-3](https://doi.org/10.1016/S0140-6736(21)01701-3).

-   Ginès, Pere, Laurent Castera, Frank Lammert, Isabel Graupera, **Miquel Serra-Burriel**, Alina M. Allen, Vincent Wai Sun Wong, Phillipp Hartmann,Maja Thiele, Llorenç Caballeria, Robert J. de Knegt, Ivica Grgurevic,Salvador Augustin, Emmanuel A. Tsochatzis, Jörn M. Schattenberg, IndraNeil Guha, Andrea Martini, Rosa M. Morillas, MontserratGarcia-Retortillo, Harry J. de Koning, Núria Fabrellas, Judit Pich, AnnT. Ma, M. Alba Diaz, Dominique Roulot, Philip N. Newsome, Michael Manns,Patrick S. Kamath, and Aleksander Krag. 2022. "Population Screening for Liver Fibrosis: Toward Early Diagnosis and Intervention for Chronic Liver Diseases." *Hepatology*. John Wiley; Sons Inc. doi:[10.1002/hep.32163](https://doi.org/10.1002/hep.32163).

-   Joshi, Rushikesh S, Darryl Lau, Justin K Scheer, **Miquel Serra-Burriel**, Alba Vila-Casademunt, Shay Bess, Justin S Smith, Ferran Pellise, and Christopher P Ames. 2021. "State-of-the-Art Reviews Predictive Modeling in Adult Spinal Deformity: Applications of Advanced Analytics." *Spine Deformity* 9: 1223--39. doi:[10.1007/s43390-021-00360-0](https://doi.org/10.1007/s43390-021-00360-0).

-   Solà, Elsa, Elisa Pose, Daniela Campion, Salvatore Piano, Olivier Roux,Macarena Simon-Talero, Frank Uschner, Koos de Wit, Giacomo Zaccherini,Carlo Alessandria, Ulrich Beuers, Paolo Caraceni, Claire Francoz,Rajeshwar P. Mookerjee, Jonel Trebicka, Victor Vargas, **Miquel Serra-Burriel**, Ferran Torres, Sara Montagnese, Aleksander Krag, Ruben Hernaez, MarkoKorenjak, Hugh Watson, Juan G. Abraldes, Patrick S. Kamath, Pere Ginès,F. Durand, M. Bernardi, C. Solé, J. Pich, I. Graupera, L. Napoleone, C.Jiménez, A. Juanola, E. Avitabile, A. Ma, N. Fabrellas, M. Carol, E.Palacio, M. Aban, T. Lanzillotti, G. Nicolao, M. T. Chiappa, V. Esnault,A. Forner, S. Graf-Dirmeier, J. Helder, M. Lopez, M. Cervera, and M.Pérez-Guasch. 2021. "Endpoints and Design of Clinical Trials in Patients with Decompensated Cirrhosis: Position Paper of the LiverHope Consortium." *Journal of Hepatology* 74 (1): 200--219.doi:<https://doi.org/10.1016/j.jhep.2020.08.009>.

# Book chapters

-   **Serra-Burriel, Miquel**, and Christopher Ames. 2022. "Machine Learning-Based Clustering Analysis: Foundational Concepts, Methods, and Applications." In *Machine Learning in ClinicalNeuroscience*, edited by Victor E. Staartjes, Luca Regli, and Carlo Serra, 91--100. Cham: Springer International Publishing.

## 
