---
title: "Teaching"
---

-   Term Course: Advanced Medical Research Methods. UZH Life Sciences PhD programme; Fall 2021-22-23-24.

-   Term Course: Methods Seminar. UZH Life Sciences PhD programme; Spring 2022.

-   Term Course: Research methods for studies on human health and disease UZH (Class). Fall 2023-24.

-   Block Course: Introduction to causal inference -- EBPI UZH; November 2022.

-   Block Course: The impacts of policies on health outcomes: Instructor -- BGSE Microeconometrics summer school; June 2019 & June 2021

-   Block Course: Use of real-world data for health services and health policy research: Instructor -- IACS; May 2018 & May 2019

-   Block Course: Hospital performance evaluation: Instructor -- AEETS; November 2018

-   Block Course: Evidence-based surgery: Inference in non-experimental data: Instructor -- VHIR; June 2018

-   Block Course: The economics of antimicrobial resistance: Instructor -- ISGlobal summer school; July 2017

If you would like to obtain the materials please send an email.
